export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ABOUT_ROUTE = '/about'
export const WISHLIST_ROUTE = '/wishlist'
export const ITEMS_ROUTE = '/items/:id'
export const HOME_ROUTE = '/'
export const NOT_FOUND_ROUTE = '*'
export const SEARCH_IMAGES_ROUTE = '/search_images'
export const FIREBASE_ROUTE = '/firebase'

